language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3

sudo: false

matrix:
  include:
    - php: 8.2
      env:
        - CARBON_PRE_RELEASE='yes'

before_install:
  - travis_retry composer self-update

install:
  - if [[ $CARBON_PRE_RELEASE == "yes" ]]; then travis_retry composer require nesbot/carbon=dev-master; fi;
  - travis_retry composer update --dev --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
